# -*- coding: utf-8 -*-
"""dio_desafio_pyhton_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DI9gxRmiW71FcU3iH62Y5z4RaS1u8_j
"""

#importando as bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
plt.style.use("seaborn-v0_8-darkgrid")

'''
leitura da base de dados
fonte: Guilherme Albuquerque - https://www.kaggle.com/datasets/guilhermegoncalves/vacinao-brasil-microdados
feito uma filtragem para apenas os dados de volta redonda e vacinados
gerado o arquivo volta_redonda_vacina.csv
'''
volta_redonda = pd.read_csv('volta_redonda_vacina.csv', parse_dates=['data_aplicacao'])

volta_redonda.info()

#fazer um drop nas linhas na qual data_aplicacao está vazia
volta_redonda.dropna(subset=['data_aplicacao'], inplace=True)
#volta_redonda = volta_redonda.drop(['data_aplicacao'], axis=1, inplace=True)

volta_redonda.info()

volta_redonda.groupby([volta_redonda["data_aplicacao"].dt.month, volta_redonda['paciente_sexo_biologico']])['vacina'].count()

volta_redonda.groupby([volta_redonda["data_aplicacao"].dt.month, volta_redonda['estabelecimento']])['vacina'].count()

volta_redonda.groupby([volta_redonda['estabelecimento']])['vacina'].count().sort_values(ascending=True).plot.barh(title="Total Produtos Vendidos")
plt.xlabel("Unidade de Saúde")
plt.ylabel("Quantidade");

volta_redonda.groupby([volta_redonda['paciente_sexo_biologico']])['vacina'].count().sort_values(ascending=True).plot.bar(title="Total Vacinas por Sexo")
plt.xlabel("Sexo")
plt.ylabel("Quantidade")
plt.xticks(rotation='horizontal');

volta_redonda.groupby([volta_redonda['paciente_subgrupo']])['vacina'].count().loc[lambda x: x > 400].sort_values(ascending=True).plot.barh(title="Total Vacinas por pacientes > 400 aplicações")
plt.xlabel("Quantidade")
plt.ylabel("Paciente")
plt.xticks(rotation='horizontal');

volta_redonda.groupby([volta_redonda["data_aplicacao"]])['vacina'].count().plot(marker='o')
plt.xlabel("Mês")
plt.ylabel("Vacinas");